# Generated by Django 4.1.2 on 2022-10-25 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RenameField(
            model_name='node',
            old_name='node_order_indaex',
            new_name='node_order_index',
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(help_text='Keep the name short, ideally one word.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Letters, numbers and '&' only plus must start with a letter.", regex='^[\\w][a-zA-Z &]+$'), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
