# Generated by Django 3.2.16 on 2022-10-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('blog', '0009_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
