# Generated by Django 3.2.16 on 2022-10-28 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_delete_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='Article',
        ),
    ]
