# Generated by Django 3.2.16 on 2022-10-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogindexpage_search_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
