# Generated by Django 3.2.16 on 2022-11-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20221101_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
    ]
