# Generated by Django 3.2.16 on 2022-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_article_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
