# Generated by Django 3.2.16 on 2022-11-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221101_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='search_image',
        ),
    ]
