# Generated by Django 3.2.16 on 2022-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_pyblogsitespecificsettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyblogsitespecificsettings',
            name='header_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
