# Generated by Django 3.2.16 on 2022-11-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pyblogsitespecificsettings_header_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyblogsitespecificsettings',
            name='youtube',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
    ]
