# Generated by Django 3.2.16 on 2022-11-03 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('base', '0012_alter_pyblogsitespecificsettings_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyblogsitespecificsettings',
            name='bread_image',
            field=models.ForeignKey(blank=True, help_text='Bread Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
