# Generated by Django 3.2.16 on 2022-11-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_pyblogsitespecificsettings_bread_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyblogsitespecificsettings',
            name='comments_code',
            field=models.TextField(blank=True, help_text='Code for comments code'),
        ),
        migrations.AddField(
            model_name='pyblogsitespecificsettings',
            name='google_code',
            field=models.TextField(blank=True, help_text='Google code for head page'),
        ),
    ]
