# Generated by Django 3.2.16 on 2022-11-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20221103_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyblogsitespecificsettings',
            name='comments_code',
            field=models.CharField(blank=True, max_length=500, verbose_name='Code for comments code'),
        ),
    ]
