# Generated by Django 3.2.16 on 2022-11-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_pyblogsitespecificsettings_comments_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyblogsitespecificsettings',
            name='comments_code',
            field=models.TextField(blank=True, help_text='Code for comments code'),
        ),
    ]
